local root = vim.env.TEST_ROOT or vim.fn.getcwd()
local directory = vim.fn.tempname()
vim.fn.mkdir(directory, "p")
local path = directory .. "/herdr-scrollback-startup.txt"
vim.fn.writefile({ "startup" }, path)
vim.cmd.edit(vim.fn.fnameescape(path))
dofile(root .. "/config/nvim/lua/config/autocmds.lua")
vim.wait(1000, function() return vim.b.scrollback_setup_done == true end)
assert(vim.b.scrollback_setup_done == true, "startup scrollback buffer was not replayed")
assert(vim.bo.buftype == "nofile" and not vim.bo.modifiable, "scrollback options missing")
assert(vim.fn.maparg("q", "n") == "<Cmd>quit!<CR>", "q does not use quit!")

local later = vim.fn.tempname():gsub("[^/]+$", "herdr-scrollback-later.txt")
vim.fn.writefile({ "later" }, later)
vim.cmd.edit(vim.fn.fnameescape(later))
vim.wait(1000, function() return vim.b.scrollback_setup_done == true end)
assert(vim.b.scrollback_setup_done == true, "later scrollback buffer was not handled")

vim.cmd.enew()
vim.api.nvim_buf_set_name(0, root .. "/herdr-scrollback-outside.txt")
vim.api.nvim_exec_autocmds("BufReadPost", { buffer = 0 })
vim.wait(20)
assert(vim.b.scrollback_setup_done == nil, "scrollback outside the temporary directory was handled")

local modified = vim.fn.tempname():gsub("[^/]+$", "herdr-scrollback-modified.txt")
vim.fn.writefile({ "modified" }, modified)
vim.cmd.edit(vim.fn.fnameescape(modified))
vim.api.nvim_buf_set_lines(0, 0, -1, false, { "unsaved" })
vim.wait(20)
assert(vim.bo.modified and vim.b.scrollback_setup_done == nil, "unsaved scrollback buffer was replaced")
vim.fn.delete(later)
vim.fn.delete(modified)
vim.fn.delete(directory, "rf")
